### ISSUE TITLE
[O0] Bug: usuário no primeiro acesso não é direcionado para reset de senha

### ISSUE THREAD

**Issue by MarquesEmiLly** [aceleradora-TW/acelera-mais-front#161]
# Contexto
Após usuário ser criado pelo admin é enviado os dados para primeiro login na aplicação, se o usuário não tiver um token (válido ou inválido) e role = admin ele não conseguirá acessar a página de reset.
Não é salvo dados de token, role e name no Local Storage quando o usuário acessa pela primeira vez.

# Para reproduzir
- Criar usuário novo pelo admin
- Fazer login a partir do e-mail de convite usando aba anônima
> Usuáio não é direcionado para a página de troca de senha (na verdade é direciona mas sai rapidamente)

# Notas técnicas
- Ao acessar a página de login deverá certificar que não haja token (válido ou inválido) e role diferente de admin no local storage.
- No front-end acessar src > pages > authentication > forms > login > index.js

**Comment by talesacademico** [comment]
# Contexto
Após usuário ser criado pelo admin é enviado os dados para primeiro login na aplicação, se o usuário não tiver um token (válido ou inválido) e role = admin ele não conseguirá acessar a página de reset.
Não é salvo dados de token, role e name no Local Storage quando o usuário acessa pela primeira vez.

# Critérios
- [ ] Deverá criar um novo mentor-avaliador
- [ ] Ao acessar a página de login deverá certificar que não haja token (válido ou inválido) e role diferente de admin no local storage.
- [ ] Fazer login com as credenciais disponibilizadas no email pelo admin
- [ ] Acessar a página de reset senha

# Como Chegar lá
No front-end acessar src > pages > authentication > forms > login > index.js
